apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato
  labels:
    app: zomato
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
      - name: zomato
        image: 322113025631.dkr.ecr.ap-south-1.amazonaws.com/food-delivery-app:latest
        ports:
        - containerPort: 3000
